name: Digital Metadata Standards at the Hesburgh Libraries
description: Our metadata standards for digital documents and media.
markdown: redcarpet
permalink: /:categories/:title/
pygments: false
exclude:
  - '.ruby-version'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'README.md'

