webhost:  'ndlib.github.io'
baseurl:  '/metadata_application_profile'
markdown:  redcarpet
permalink: /:categories/:title/
pygments:  false
exclude:
  - '.ruby-version'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'README.md'

name: Digital Metadata Standards at the Hesburgh Libraries
description: Our metadata standards for digital documents and media.
